---
- name: "Playing with Ansible and Helm"
  hosts: localhost
  connection: local 
  gather_facts: false
  tasks:

    - name: Add chart repo
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: "https://charts.bitnami.com/bitnami"

    - name: Install Helm postgres
      kubernetes.core.helm:
        name: postgres
        chart_ref: bitnami/postgres
        release_namespace: postgres
